name: "GitGuardian Shield Action"
description: "Scan commits for secrets and other issues."
author: GitGuardian <nitichaisawangsai@gitguardian.com>

inputs:
  args:
    description: |
      Arguments to be passed to gg-shield scan
      Options:
        --show-secrets  Show secrets in plaintext instead of hiding them.
        --exit-zero     Always return a 0 (non-error) status code, even if issues
                        are found. The env var GITGUARDIAN_EXIT_ZERO can also be used
                        to set this option.
        --all-policies  Present fails of all policies (Filenames, FileExtensions,
                        Secret Detection). By default, only Secret Detection is
                        shown.
        -v, --verbose   Verbose display mode.
    required: false
branding:
  icon: "shield"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}