name: "GitGuardian Scan"

# Trigger on push
on:
  push:
    branches: 
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          echo "- in before ${{ github.event.before }}!"
          echo "- in base ${{ github.event.base }}!"
          echo "- in sha ${{ github.event.pull_request.base.sha }}!"
          echo "- in default_branch ${{ github.event.repository.default_branch }}!"
          echo "- in GITGUARDIAN_API_KEY ${{ secrets.GITGUARDIAN_API_KEY }}!"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
