name: Lint

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  run-lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        run: yarn run lint