name: Bump version Git
on:
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.tagging.outputs.new_version }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub Tag version
        uses: ncipollo/release-action@v1
        with:
          # tag: ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tagging.outputs.new_version }}
          name: Release ${{ steps.tagging.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}