name: Bump version Git
on:
  push:
    branches:
      - develop
      - master
jobs:
  build:
    needs: [run-lint, run-test]
    name: Build a docker image
    runs-on: ubuntu-latest
    outputs:
      tag_version: '${{ steps.tagging.outputs.new_version }}'
    steps:
      - uses: actions/checkout@v3
      - id: tagging
        name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          release_branches: master
          pre_release_branches: develop
          default_bump: patch
          fetch_all_tags: true