name: End-to-end test

on:
  push:
    branches: 
      - release

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      # action clones the repository into this environment, 
      # making your code available for the workflow steps that follow.
      - name: Checkout Repository B
        uses: actions/checkout@v3
        with:
          repository: NitichaiSawangsai/cypress-ex1  # เปลี่ยนเป็น repository ของคุณ
          ref: release  # ตรวจสอบจาก branch release
          # token: ${{ secrets.REPO_B_ACCESS_TOKEN }}  # ใช้ Personal Access Token ที่มีสิทธิ์ในการอ่าน Repository B

      - name: Install Dependencies
        run: npm install  # ติดตั้ง dependencies ของ Cypress

      - name: Run E2E Tests with Cypress
        run: npm run cy:run  # แก้ตามคำสั่งที่ใช้ใน Repository B สำหรับรัน Cypress tests

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos


