name: Run Test E2E Required Input
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Version tag or branch to test'
        required: true
        default: 'master'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Test E2E
        uses: actions/checkout@v4
        with:
          repository: NitichaiSawangsai/cypress-ex1  
          ref: ${{ github.event.inputs.version-tag }} 
          token: ${{ github.token }}

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos